Add notification & poll support
cberner/fuser pull request #265
Opened 2023-11-04 02:47 UTC by zevweiss

This patch series adds support for `poll()` and most of the currently-existing FUSE notification types (unsolicited messages sent by userspace to notify the kernel of various events).  It addresses issues #16, #17, and #160.

Not currently implemented are the `FUSE_EXPIRE_ONLY` flag for the `FUSE_NOTIFY_INVAL_ENTRY` operation (mostly just because it seems fairly niche and I had no particular need for it) and the `FUSE_NOTIFY_RETRIEVE` operation (since it involves bidirectional communication that would complicate the implementation).

I've also translated some of libfuse's example programs to exercise this functionality (see [this commit](https://github.com/zevweiss/fuser/commit/2fdc458cb7bda1c4d84933a21e1f94961a7a3e21) in my fork), though I haven't included them in this PR since they're directly derived from GPL code and are hence GPLed themselves, and I'm not sure what this project's feelings toward that would be -- if per-file exceptions for example programs would be acceptable I can add them as well.

2023-11-04 21:22 UTC, cberner requested changes
Two minor comments.

Also, yes please go ahead and add an example to the `examples/` folder. Having a separate GPL license for that file(s) is fine, as long as it's only in `examples/`

Excited to have this implemented!

2023-11-04 21:52 UTC, zevweiss commented on examples/simple.rs
> +// use fuser::consts::FUSE_WRITE_KILL_PRIV;
The reasoning is mentioned in the commit message for commit 57cb8ef (if a bit confusingly, given the dual meanings of "use"):

> The use of FUSE_WRITE_KILL_PRIV is commented out, so comment out the
'use' for it as well, ...

Looking back in the git history, that commenting-out dates to commit 244547538cdc1ade2a268625600d44070d4b4049, when the commented-out use of it was added along with a non-commented `use` statement.

2023-11-04 21:52 UTC, zevweiss commented on src/notify.rs
> +    pub fn store(&self, ino: u64, offset: u64, data: &[u8]) -> io::Result<()> {
`i64` would be consistent with the `off_t` in libfuse and other offset parameters elsewhere (e.g.  in `fuse_notify_inval_inode_out`), but in this particular case the [kernel's uapi header](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/fuse.h?h=v6.6#n1027) and [the existing definition of `fuse_notify_store_out`](https://github.com/cberner/fuser/blob/8b390279a5da98df3f91b69aee8ef20de793a2fa/src/ll/fuse_abi.rs#L1080) both have it unsigned.  I'm not sure offhand about the reasoning for it (if there is any), but I stuck with what was there.  Thoughts?

2023-11-04 21:56 UTC, cberner commented on src/notify.rs
> +    pub fn store(&self, ino: u64, offset: u64, data: &[u8]) -> io::Result<()> {
Ah, let's leave it this way then

2023-11-04 21:57 UTC, cberner approved these changes

2023-11-04 22:19 UTC, zevweiss commented
Any opinions on a preferred fix for the CI failure?  I'm not entirely certain of the purpose of the first `cargo build` that it's failing on there (just a toolchain/build.rs sanity check?); should we just add `examples/` to the first `ADD` line?

2023-11-04 22:32 UTC, cberner commented
Ah, you can just change the Docker file so that it only builds the `simple` example binary. It uses that for running the tests

2023-11-04 22:34 UTC, cberner commented
Or just deleting lines 20 and 21 would be fine too. That looks like a silly hack I added a while ago to make the Dockerfile build faster =P

2023-11-04 22:36 UTC, zevweiss commented
Ah, okay -- I'll try just removing them.  (Unfortunately it looks like tweaking cargo command-line flags wouldn't work -- apparently it tries to find the files for any `[[example]]` sections unconditionally, and just treats anything missing as a hard parse failure no matter what flags are or aren't passed...)

2023-11-04 23:50 UTC, merged

2023-11-04 23:51 UTC, cberner commented
Merged. Thanks!

2023-12-23 16:37 UTC, chris-laplante commented
Thanks for this! Was just planning on implementing it myself :). Glad to see someone else did it.