Add file handle for get_attr requests.
cberner/fuser pull request #279
Opened 2024-03-25 18:59 UTC by IamTheCarl

This PR adds the file handle parameter to the `getattr` request.
This feature is necessary when implementing filesystem APIs that generate file contents on request, like `/proc`.
The correct length of the file must be returned by `getattr` for that specific instance of the generated file, otherwise most programs will not read the file correctly. A file handle is needed to know which instance we are getting attributes for.

The parameter is available in ABI 7-9 and above, and has been feature gated as such. When the feature is not enabled, the `getattr` method on Filesystems will always be passed None for the file descriptor.

2024-03-26 04:36 UTC, cberner requested changes
One minor style comment

2024-03-26 04:36 UTC, cberner commented on examples/hello.rs
> +    fn getattr(&mut self, _req: &Request, ino: u64, _fd: Option<u64>, reply: ReplyAttr) {
Can you name these `_fh` to match the rest of the code? Same comment for the other examples

2024-03-27 02:40 UTC, cberner requested changes

2024-03-27 02:40 UTC, cberner commented on src/lib.rs
> +    fn getattr(&mut self, _req: &Request<'_>, ino: u64, fd: Option<u64>, reply: ReplyAttr) {
You missed one. Otherwise this lgtm

2024-03-27 14:48 UTC, cberner approved these changes

2024-03-28 02:58 UTC, merged

2024-03-28 16:23 UTC, IamTheCarl commented
Thank you!